main:
	gcc -g -o  enc_server enc_server.c
	gcc -g -o  enc_client enc_client.c
	gcc -g -o dec_server dec_server.c
	gcc -g -o dec_client dec_client.c
	gcc -o keygen keygen.c

clean:
	 rm -rf enc_server enc_client dec_server dec_client keygen
